//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legion.app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegionDetail
    {
        public int Legion_ID { get; set; }
        public string Legion_Name { get; set; }
        public string Legion_Color { get; set; }
        public string Primarch_Status { get; set; }
    
        public virtual LegionRef LegionRef { get; set; }
    }
}
