//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legion.app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegionRef
    {
        public int Ref_Legion_ID { get; set; }
        public string Legion_Primarch_Name { get; set; }
        public string Loyal_or_Heretic { get; set; }
    
        public virtual LegionDetail LegionDetail { get; set; }
    }
}
